---
title: "Cousera JH - Prediction Motivation"
author: "Sejin Park"
date: "2015. 9. 14."
output:
  html_document:
    keep_md: yes
---

The goal of your project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. You may use any of the other variables to predict with. You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases. 

1. Your submission should consist of a link to a Github repo with your R markdown and compiled HTML file describing your analysis. Please constrain the text of the writeup to < 2000 words and the number of figures to be less than 5. It will make it easier for the graders if you submit a repo with a gh-pages branch so the HTML page can be viewed online (and you always want to make it easy on graders :-).
2. You should also apply your machine learning algorithm to the 20 test cases available in the test data above. Please submit your predictions in appropriate format to the programming assignment for automated grading. See the programming assignment for additional details. 


```{r}

fileURL.tr <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
fileURL.test <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
download.file(fileURL.tr, "pml-training.csv")
download.file(fileURL.test, "pml-testing.csv")

pml.training <- read.csv("pml-training.csv", header=T,stringsAsFactors = F)
str(pml.training)
pml.testing <-  read.csv("pml-testing.csv", header=T,stringsAsFactors = F)
```

